global:
  scrape_interval:     5s
  evaluation_interval: 5s
  scrape_timeout:      4s

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

rule_files:
  - "aegis_alert_rules.yml"

scrape_configs:

  - job_name: "aegisnode_fl_server"
    metrics_path: "/metrics"
    scrape_interval: 5s
    static_configs:
      - targets: ["localhost:8000"]
        labels:                        # ← moved INSIDE static_configs
          environment: "hackathon"
          component:   "fl_server"

  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
